### ISSUE TITLE
Hi bro, can you tell me how can I run this application on my local machine

### ISSUE THREAD

**Issue by Jeetu-Kumar** [wdesgardin/twitter-clone#1]

**Comment by Jeetu-Kumar** [comment]
Please help me. And I'm using .net 6 to run this

**Comment by wdesgardin** [comment]
You need to install the .NET 5 sdk https://dotnet.microsoft.com/en-us/download/dotnet/5.0 as well as NodeJS LTS https://nodejs.org/en/.

Then run the command `npm i` within the src/WebUI/ClientApp folder, then start the api project using Visual Studio or with the command `dotnet run` within src/WebUI

**Comment by Jeetu-Kumar** [comment]
Thank you for your help sir. I was not expecting your reply because you know many technology & things and I'm in learning phase. Thank u again.
